<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>OPAC</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" Version="10.1.0" />
    <PackageReference Include="Volo.Abp.Authorization" Version="10.1.0" />
    <ProjectReference Include="..\OPAC.Domain.Shared\OPAC.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
