<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>MainPlatform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MainPlatform.Domain\MainPlatform.Domain.csproj" />
    <ProjectReference Include="..\MainPlatform.TestBase\MainPlatform.TestBase.csproj" />
    <ProjectReference Include="..\..\modules\OPAC\src\OPAC.Domain\OPAC.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

</Project>
