<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Collaboration</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Mapperly" Version="10.1.0" />
    <PackageReference Include="Volo.Abp.Ddd.Application" Version="10.1.0" />
    <ProjectReference Include="..\Collaboration.Application.Contracts\Collaboration.Application.Contracts.csproj" />
    <ProjectReference Include="..\Collaboration.Domain\Collaboration.Domain.csproj" />
  </ItemGroup>

</Project>
