<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>MainPlatform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MainPlatform.Application\MainPlatform.Application.csproj" />
    <ProjectReference Include="..\MainPlatform.Domain.Tests\MainPlatform.Domain.Tests.csproj" />
    <ProjectReference Include="..\..\modules\OPAC\src\OPAC.Application\OPAC.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

</Project>
